// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkuqckfhhhhakjoiynkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdXFja2ZoaGhoYWtqb2l5bmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTkyMjAsImV4cCI6MjA2NTk5NTIyMH0.PVIj4JdZsdZYVT7qPbmNYDFaSv44I5k1PwuWCkwwQ8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);